# Generated by Django 4.2.26 on 2025-12-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_update_materialitem_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentMaterialItem',
            fields=[
            ],
            options={
                'verbose_name': 'Навеска (каталог)',
                'verbose_name_plural': 'Навеска (каталог)',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.materialitem',),
        ),
        migrations.CreateModel(
            name='SoilItem',
            fields=[
            ],
            options={
                'verbose_name': 'Грунт',
                'verbose_name_plural': 'Грунт',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.materialitem',),
        ),
        migrations.CreateModel(
            name='ToolItem',
            fields=[
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.materialitem',),
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Навеска', 'verbose_name_plural': 'Навески'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['code'], 'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Запись обслуживания', 'verbose_name_plural': 'Записи обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='materialitem',
            options={'ordering': ['name'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='equipment',
            field=models.ForeignKey(help_text='Техника, к которой относится навеска', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.equipment', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(help_text='Название навески', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='pricing_modifier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Модификатор цены в процентах (например, 10 = +10%)', max_digits=6, verbose_name='Модификатор цены'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('busy', 'Занята'), ('maintenance', 'На обслуживании'), ('inactive', 'Неактивна')], default='available', help_text='Текущий статус навески', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные атрибуты', verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(help_text='Уникальный код техники', max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость аренды за день', max_digits=10, null=True, verbose_name='Дневная ставка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание техники', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Расход топлива (л/час)', max_digits=6, null=True, verbose_name='Расход топлива'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость аренды за час', max_digits=10, verbose_name='Почасовая ставка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_maintenance_date',
            field=models.DateField(blank=True, help_text='Дата последнего технического обслуживания', null=True, verbose_name='Дата последнего обслуживания'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Название техники', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Список фотографий техники', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('busy', 'Занята'), ('maintenance', 'На обслуживании'), ('inactive', 'Неактивна')], default='available', help_text='Текущий статус техники', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Список прикреплённых файлов', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость обслуживания', max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(blank=True, help_text='Описание выполненных работ', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(help_text='Техника, для которой выполнено обслуживание', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='catalog.equipment', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, help_text='Пробег на момент обслуживания', null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_at',
            field=models.DateField(help_text='Дата выполнения обслуживания', verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Плотность материала', max_digits=6, null=True, verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Материал активен и доступен для заказа', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='name',
            field=models.CharField(help_text='Название материала', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за единицу', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='supplier',
            field=models.CharField(blank=True, help_text='Поставщик материала', max_length=255, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='unit',
            field=models.CharField(default='m3', help_text='Единица измерения', max_length=32, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Описание категории', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(help_text='Название категории услуг', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.ForeignKey(help_text='Категория услуги', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.servicecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='default_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Длительность по умолчанию', max_digits=8, null=True, verbose_name='Длительность по умолчанию'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='included_items',
            field=models.JSONField(blank=True, default=list, help_text='Список включённых элементов', verbose_name='Включённые элементы'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Услуга активна и доступна для заказа', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='name',
            field=models.CharField(help_text='Название услуги', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена услуги (необязательно, услуга может не иметь фиксированной цены)', max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='unit',
            field=models.CharField(default='hour', help_text='Единица измерения', max_length=32, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
    ]
