# Generated by Django 4.2.26 on 2025-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken_notificationlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_user_id_d1d348_idx',
            old_name='notificatio_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_event_t_988cb5_idx',
            old_name='notificatio_event_t_created_idx',
        ),
    ]
