# Generated by Django 4.2.26 on 2025-12-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_rename_notificatio_user_id_status_idx_notificatio_user_id_d1d348_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-last_active_at'], 'verbose_name': 'Токен устройства', 'verbose_name_plural': 'Токены устройств'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог уведомлений', 'verbose_name_plural': 'Логи уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='notificationsubscription',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Подписка на уведомления', 'verbose_name_plural': 'Подписки на уведомления'},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='app_version',
            field=models.CharField(blank=True, help_text='Версия мобильного приложения', max_length=20, verbose_name='Версия приложения'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания токена', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_info',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительная информация об устройстве', verbose_name='Информация об устройстве'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последней активности', verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], help_text='Платформа устройства', max_length=20, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(db_index=True, help_text='FCM токен устройства', max_length=255, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, которому принадлежит токен', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('push', 'Push-уведомление'), ('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], help_text='Канал уведомлений', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания лога', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='endpoint',
            field=models.CharField(help_text='Адрес доставки уведомления', max_length=255, verbose_name='Конечная точка'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Текст ошибки, если отправка не удалась', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(help_text='Тип события (order_created, status_changed, payment_received)', max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='payload',
            field=models.JSONField(default=dict, help_text='Данные уведомления', verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Количество попыток отправки', verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время успешной отправки', null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', help_text='Статус отправки уведомления', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому отправлялось уведомление', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='channel',
            field=models.CharField(choices=[('push', 'Push-уведомление'), ('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], help_text='Канал уведомлений', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания подписки', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Подписка активна', verbose_name='Включена'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='endpoint',
            field=models.CharField(help_text='Device token / email / chat id', max_length=255, verbose_name='Конечная точка'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего использования', null=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Настройки подписки', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, для которого настроена подписка', on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
