# Generated by Django 4.2.26 on 2025-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_order_status_77f1e6_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_start_d_1feb61_idx',
            old_name='orders_order_start_d_75e6fe_idx',
        ),
    ]
