# Generated by Django 4.2.26 on 2025-12-02 18:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_options_alter_client_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_rename_orders_order_status_77f1e6_idx_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог изменения статуса', 'verbose_name_plural': 'Логи изменений статусов'},
        ),
        migrations.AlterModelOptions(
            name='photoevidence',
            options={'verbose_name': 'Фото-доказательство', 'verbose_name_plural': 'Фото-доказательства'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Адрес выполнения работ', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Список вложенных файлов', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Клиент, для которого выполняется заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, создавший заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание заказа', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_dt',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания работ', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='geo_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота', max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Менеджер, ответственный за заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='Уникальный номер заказа', max_length=32, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Оператор, выполняющий заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сумма предоплаты', max_digits=12, verbose_name='Сумма предоплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment_status',
            field=models.CharField(default='pending', help_text='Статус предоплаты', max_length=20, verbose_name='Статус предоплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON снимок расчёта стоимости', verbose_name='Снимок расчёта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_dt',
            field=models.DateTimeField(help_text='Дата и время начала работ', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создан'), ('APPROVED', 'Одобрен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], default='CREATED', help_text='Текущий статус заказа', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая сумма заказа', max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Скидка в процентах', max_digits=6, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('equipment', 'Техника'), ('service', 'Услуга'), ('material', 'Материал'), ('attachment', 'Навеска')], help_text='Тип позиции заказа', max_length=20, verbose_name='Тип позиции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name_snapshot',
            field=models.CharField(help_text='Название позиции', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Заказ, к которому относится позиция', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Количество единиц', max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID элемента в исходной таблице', null=True, verbose_name='ID в исходной таблице'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Налоговая ставка в процентах', max_digits=5, verbose_name='Налоговая ставка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Единица измерения (час, день, шт.)', max_length=32, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за единицу измерения', max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='actor',
            field=models.ForeignKey(help_text='Пользователь, изменивший статус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='URL прикреплённого файла', verbose_name='URL вложения'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к изменению статуса', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время изменения статуса', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создан'), ('APPROVED', 'Одобрен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], help_text='Предыдущий статус', max_length=20, verbose_name='Старый статус'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(help_text='Заказ, для которого изменён статус', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создан'), ('APPROVED', 'Одобрен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], help_text='Новый статус заказа', max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время съёмки', null=True, verbose_name='Дата съёмки'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='file_url',
            field=models.URLField(help_text='URL фотографии', verbose_name='URL файла'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта места съёмки', max_digits=9, null=True, verbose_name='Широта GPS'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота места съёмки', max_digits=9, null=True, verbose_name='Долгота GPS'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные примечания к фото', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='order',
            field=models.ForeignKey(help_text='Заказ, к которому относится фото', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='photo_type',
            field=models.CharField(choices=[('before', 'До работ'), ('after', 'После работ'), ('incident', 'Инцидент')], default='before', help_text='Тип фотографии', max_length=20, verbose_name='Тип фото'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='photoevidence',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Пользователь, загрузивший фото', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
