# Generated by Django 4.2.27 on 2025-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fuel_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Расходы на топливо для данной техники', max_digits=12, null=True, verbose_name='Расходы на топливо'),
        ),
    ]
