# Generated by Django 4.2.27 on 2025-12-06 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_add_fuel_expense_to_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operators',
            field=models.ManyToManyField(blank=True, help_text='Операторы, выполняющие заказ', related_name='operated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Операторы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Оператор, выполняющий заказ (устаревшее поле, используйте operators)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_orders_legacy', to=settings.AUTH_USER_MODEL, verbose_name='Оператор (устаревшее)'),
        ),
    ]
