# Generated by Django 4.2.27 on 2025-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_repair_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создан'), ('APPROVED', 'Одобрен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён'), ('DELETED', 'Удалён')], default='CREATED', help_text='Текущий статус заказа', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создан'), ('APPROVED', 'Одобрен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён'), ('DELETED', 'Удалён')], help_text='Предыдущий статус', max_length=20, verbose_name='Старый статус'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создан'), ('APPROVED', 'Одобрен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён'), ('DELETED', 'Удалён')], help_text='Новый статус заказа', max_length=20, verbose_name='Новый статус'),
        ),
    ]
