# Generated by Django 4.2.26 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес клиента', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_details',
            field=models.JSONField(blank=True, default=dict, help_text='Банковские реквизиты клиента', verbose_name='Платёжные реквизиты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, help_text='Город', max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, help_text='ФИО контактного лица', max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Адрес электронной почты', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='geo_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота', max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, help_text='ИНН организации', max_length=20, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Клиент активен', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, help_text='КПП организации', max_length=20, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Название компании или ФИО клиента', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные примечания', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Номер телефона', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
    ]
