# Generated by Django 4.2.26 on 2025-12-02 18:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
        ('finance', '0003_documenttemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ('template_type', '-version'), 'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at', '-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись зарплаты', 'verbose_name_plural': 'Записи зарплат'},
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('invoice', 'Счёт'), ('act', 'Акт'), ('receipt', 'Квитанция')], default='invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fuel', 'Топливо'), ('repair', 'Ремонт'), ('rent', 'Аренда техники'), ('other', 'Прочее')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сумма счёта', max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='RUB', help_text='Валюта счёта', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Срок оплаты счёта', null=True, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата выписки счёта', verbose_name='Дата выписки'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, help_text='Уникальный номер счёта', max_length=50, unique=True, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(help_text='Заказ, для которого выписан счёт', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возвращено')], default='pending', help_text='Статус оплаты счёта', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF файл счёта', null=True, upload_to='invoices/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL PDF файла счёта', verbose_name='URL PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн'), ('other', 'Другое')], default='bank_transfer', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возвращено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'Почасовая'), ('fixed', 'Фиксированная'), ('percent', 'Процентная')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('paid', 'Выплачена')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Дата обновления'),
        ),
    ]
