# Generated by Django 4.2.26 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_accountant_viewer_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL аватара пользователя', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='ru', help_text='Предпочитаемый язык интерфейса', max_length=8, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON снимок прав доступа', verbose_name='Снимок прав'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона пользователя', max_length=32, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Должность сотрудника', max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('operator', 'Оператор')], default='manager', help_text='Роль пользователя в системе', max_length=32, verbose_name='Роль'),
        ),
    ]
