# Generated by Django 4.2.26 on 2025-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_actor_i_ec0f72_idx',
            old_name='audit_auditl_actor_i_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity__9535bf_idx',
            old_name='audit_auditl_entity__entity__idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_766c6d_idx',
            old_name='audit_auditl_action__created_idx',
        ),
    ]
