# Generated by Django 4.2.26 on 2025-12-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_rename_audit_auditl_actor_i_created_idx_audit_audit_actor_i_ec0f72_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог аудита', 'verbose_name_plural': 'Логи аудита'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('export', 'Экспорт'), ('status_change', 'Изменение статуса'), ('file_upload', 'Загрузка файла'), ('payment', 'Платёж'), ('role_change', 'Изменение роли')], db_index=True, help_text='Тип выполненного действия', max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Пользователь, выполнивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата и время действия', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(db_index=True, help_text='ID сущности (может быть UUID)', max_length=255, verbose_name='ID сущности'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(db_index=True, help_text='Тип сущности (Order, Invoice, User, etc.)', max_length=100, verbose_name='Тип сущности'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP адрес пользователя', null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные действия (изменённые поля, значения)', verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Request ID для трейсинга', max_length=100, verbose_name='Request ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User Agent браузера', max_length=500, verbose_name='User Agent'),
        ),
    ]
